AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role for us to assume and resources to access
Parameters:
  BucketName:
    Type: String
    Default: "xanzhu-sts"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::713881790871:user/sts-machine-user'
              # Service: 
              #   - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: [
                            !Sub 'arn:aws:s3:::*',
                            !Sub 'arn:aws:s3:::${BucketName}',
                            !Sub 'arn:aws:s3:::${BucketName}/',
                ]
      