#!/usr/bin/env bash

set -e

# Create VPC

VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" --region ap-southeast-2 --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=xanzhu-vpc-1}]" --query Vpc.VpcId --output text)

echo "VPC_ID: $VPC_ID"

# Turn on DNS Hostnames
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-support "{\"Value\": true}"

# Create IGW 

IGW_ID=$(aws ec2 create-internet-gateway --query InternetGateway.InternetGatewayId --output text)

echo "IGW_ID: $IGW_ID"

# Attach IGW to VPC
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Create a new subnet

SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block "172.1.0.0/20" --query Subnet.SubnetId --output text)

echo "SUBNET_ID: $SUBNET_ID"

# Auto-assign IPV4 to address
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch

# Grab Route Table ID 
RT_ID=$(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" --query "RouteTables[].RouteTableId[]" --output text)

echo "RT_ID:$RT_ID"

# Associate subnet 
ASSOC_ID=$(aws ec2 associate-route-table --subnet-id $SUBNET_ID --route-table-id $RT_ID --query AssociationId --output text)

echo "ASSOC_ID: $ASSOC_ID"

# Add route for route table to IGW
aws ec2 create-route --route-table-id $RT_ID --destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID

# Print out deletion commands
echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID $ASSOC_ID $RT_ID"