#!/usr/bin/env bash

set -e

# Check if the argument is not provided 
if [ -z "$1" ]; then
    echo "Usage: delete_vpc <vpc_id>"
    else 
        export VPC_ID="$1"
fi

if [ -z "$2" ]; then
    echo "Usage: delete_vpc <IGW_ID>"
    else 
        export IGW_ID="$2"
fi

if [ -z "$3" ]; then
    echo "Usage: delete_vpc <subnet_id>"
    else 
        export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
    echo "Usage: delete_vpc <subnet_id>"
    else 
        export ASSOC_ID="$4"
fi

if [ -z "$5" ]; then
    echo "Usage: delete_vpc <rt_id>"
    else 
        export RT_ID="$5"
fi


# Notes Cannot find Variables need to find them first LOL

# detach the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete the IGW

# dissaociate subnet

aws ec2 disassociate-route-table --association-id $ASSOC_ID

# delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

# delete route table
# aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc

aws ec2 delete-vpc --vpc-id $VPC_ID