#!/usr/bin/env bash

echo "== delete objects =="

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# List objects and process with jq
aws s3api list-objects-v2 \
    --bucket "$BUCKET_NAME" \
    --region us-east-1 \
    --query "Contents[].Key" \
    --output json | jq -n '{Objects: [inputs | .[] | {Key: .}]}'