#! /usr/bin/env bash

echo "== put object =="

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a file name prefix eg. ./bucket my-bucket-name my-file-prefix"
    exit 1
fi


BUCKET_NAME=$1
FILENAME=$2

OBJECTKEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECTKEY