#! /usr/bin/env bash

echo == sync files ==

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a file name prefix eg. ./bucket my-bucket-name my-file-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME_PREFIX=$2

# Storage of files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#Delete folder if exists already
rm -r $OUTPUT_DIR

# Output Folder
mkdir -p $OUTPUT_DIR

# Generation random files
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do

    # Generate random file
    FILENAME=$OUTPUT_DIR/$FILE_NAME_PREFIX-$i.txt


    dd if=/dev/urandom of=$FILENAME bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files